site_name: Horrifice Documentation
theme:
    name: material
    palette:
        scheme: slate
        primary: indigo
        accent: pink
    font:
        text: Roboto
        code: Roboto Mono
nav:
    - Home: index.md
    - About: about.md
plugins:
    - search
    - literate-nav
